/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        IonIcon: (typeof import('@ionic/vue'))['IonIcon'];
        IonLabel: (typeof import('@ionic/vue'))['IonLabel'];
        IonPage: (typeof import('@ionic/vue'))['IonPage'];
        IonRouterOutlet: (typeof import('@ionic/vue'))['IonRouterOutlet'];
        IonTabBar: (typeof import('@ionic/vue'))['IonTabBar'];
        IonTabButton: (typeof import('@ionic/vue'))['IonTabButton'];
        IonTabs: (typeof import('@ionic/vue'))['IonTabs'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
    }
}
