name: Build and Deploy
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout 🛎️
                uses: actions/checkout@v3
                with:
                    persist-credentials: false
            -   name: Install Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install pnpm
                uses: pnpm/action-setup@v2
                id: pnpm-install
                with:
                    version: 8
                    run_install: false
            -   name: Build
                run: |
                    npm -v
                    pnpm -v
                    pnpm install
                    pnpm run build:github
            -   name: Deploy
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}
                    branch: gh-pages
                    folder: www
